# --- !Downs
DROP TABLE "play_evolutions";
DROP TABLE "teams";
DROP TABLE "vendor_contacts_lists";
DROP TABLE "vendor_buckets";
DROP TABLE "budget_breakdowns";
DROP TABLE "vendor_contacts";
DROP TABLE "task_comments";
DROP TABLE "tasks";
DROP TABLE "projects";
DROP TABLE "clients";
DROP TABLE "users";
DROP TABLE "businesses";